### ISSUE TITLE
Deprecated set-env and add-path commands 

### ISSUE THREAD

**Issue by asbjornu** [GitTools/actions#213]
GitHub is [deprecating `set-env` and `add-path` commands](https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/), causing the GitVersion action to log the following warning when executed:

>The `set-env` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

<img width="1443" alt="image" src="https://user-images.githubusercontent.com/12283/95333611-49799000-08ad-11eb-9360-26a886548522.png">

I'm not sure what the fix is, because we are using `v1.2.6` of `@actions/core` already.

>Action authors who are using the toolkit should update the `@actions/core` package to `v1.2.6` or greater to get the updated `addPath` and `exportVariable` functions.

**Comment by asbjornu** [comment]
I was using version `0.9.2` of `gittools/actions/gitversion/execute`. Upgrading to `0.9.4` fixed the problem. 🤦‍♂️

**Comment by JohnNeville** [comment]
I am not sure if it is something in our specific environment but we are actually getting the same error despite using v0.9.4 for both the setup and execute action. 

![image](https://user-images.githubusercontent.com/11984108/95378470-f950fc80-08b1-11eb-837a-09b446e6dd69.png)

**Comment by danstis** [comment]
I am also still getting these errors on v0.9.4

**Comment by asbjornu** [comment]
This was fixed in GitTools/GitVersion#2422.

**Comment by willemduncan** [comment]
The warning still shows up, using the following config:
```yml
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.4
        with:
          versionSpec: 5.x
```

Which results in the following output:
```
Run gittools/actions/gitversion/setup@v0.9.4
Error: The `set-env` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

--------------------------
Installing GitVersion.Tool version 5.x
--------------------------
Command: dotnet tool install GitVersion.Tool --tool-path /home/runner/work/_temp/cf986213-77c5-427f-ae47-e5316b83bdd5 --version 5.5.0
/usr/bin/dotnet tool install GitVersion.Tool --tool-path /home/runner/work/_temp/cf986213-77c5-427f-ae47-e5316b83bdd5 --version 5.5.0

... snipped for brevity ...

You can invoke the tool using the following command: dotnet-gitversion
Tool 'gitversion.tool' (version '5.5.0') was successfully installed.
Error: The `set-env` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/```

Running the latest script version `0.9.4` and it loads the patched `5.5.0` release.

**Comment by asbjornu** [comment]
That's weird, @willemduncan. Thoughts,  @danielmarbach?

**Comment by arturcic** [comment]
@asbjornu  this could be because we use this for GH actions https://github.com/GitTools/actions/blob/02ac2511c1395a56eaaba8fc7fb3535241b3d898/src/agent/github/build-agent.ts#L171 that calls this https://github.com/actions/toolkit/blob/0759cdc2309acfd91b6503597dcfa02a3cee99d0/packages/core/src/core.ts#L51

**Comment by asbjornu** [comment]
Aha, nice find @arturcic. Perhaps an upgrade of the actions toolkit is enough to get rid of the problem, then?

**Comment by arturcic** [comment]
Could be

**Comment by danielmarbach** [comment]
Yes, anything that uses `set-env` will trigger this warning, unfortunately.

**Comment by asbjornu** [comment]
A bit strange that Dependabot hasn't submittet a PR with an upgrade that fixed this, then. Hm.

**Comment by jameswoodley** [comment]
Not sure if helpful, but just wanted to call out we're still seeing this on v0.9.4

```
- name: Fetch all history for all tags and branches
  run: git fetch --prune --unshallow
- name: Install GitVersion
  uses: gittools/actions/gitversion/setup@v0.9.4
  with:
    versionSpec: '5.3.x'
- name: Use GitVersion
  id: gitversion # step id used as reference for output values
  uses: gittools/actions/gitversion/execute@v0.9.4
```

**Comment by arturcic** [comment]
Can you guys use the master instead of version 0.9.4 and say if it is fixed? If so than we need to release a new version

**Comment by arturcic** [comment]
so you need to use it like this
````uses: gittools/actions/gitversion/setup@master```` and
 ````uses: gittools/actions/gitversion/execute@master````

**Comment by jameswoodley** [comment]
I'm afraid not

![image](https://user-images.githubusercontent.com/52610563/98272683-42679f80-1f89-11eb-91a4-8dc9da7c9305.png)

**Comment by arturcic** [comment]
can you install the latest version of gitversion? 5.5.0 or you can set just 5.x?

**Comment by jameswoodley** [comment]
Same:
![image](https://user-images.githubusercontent.com/52610563/98273215-eb15ff00-1f89-11eb-8dbf-66ac96de7411.png)

**Comment by arturcic** [comment]
Thank you for the input, we need to check this one

**Comment by jameswoodley** [comment]
Happy to help, just shout if you need anything else

**Comment by SamuelJohnsonMedia** [comment]
Doesn't look like the actions/core has been updated to include the change to `exportVariable` which is very strange.

**Comment by SamuelJohnsonMedia** [comment]
I think you just need to tag the master branch as a new version (v0.9.5) as I dont think that the `@master` declaration is working properly

**Comment by SamuelJohnsonMedia** [comment]
This is crazy; bumping to the new v0.9.5 didn't work either. I'm stumped

**Comment by arturcic** [comment]
We need to debug and see why it's not working

**Comment by SamuelJohnsonMedia** [comment]
@arturcic if you look at the dist/bundle files it seems they still reference the `issueCommand` and not the `issueFileCommand` as used in the newer @actions/core version. Could it be that they have not been compiled/built since the bump to the version?

**Comment by arturcic** [comment]
Hmm, interesting, thanks for the input, hope to find some time to check it

**Comment by SamuelJohnsonMedia** [comment]
I don't think the environment variables are being set anymore either; the output variables are working but not the `GitVersion_` variables it seems.

**Comment by arturcic** [comment]
@SamuelJohnsonMedia you were right, I had to re-compile and push the files, I forgot that is required before releasing. I have re-created the v0.9.5 release as the previous one was broken. Can you check now the new v0.9.5 has fixed the issue?

@jameswoodley can you also confirm it was fixed in v0.9.5?

**Comment by SamuelJohnsonMedia** [comment]
@arturcic Perfect, all working great now ... one thing I did have to change is that the environment variables now have to be referenced as upper case, e.g. `GitVersion_SemVer` should now be referenced as `GITVERSION_SEMVER`

**Comment by arturcic** [comment]
@asbjornu can you confirm is working for you? If yes please close the issue

**Comment by garyng** [comment]
Uhmmm, I'm still getting the errors on `0.9.5`...

![image](https://user-images.githubusercontent.com/4453664/98482379-ec6e5280-223b-11eb-8659-4e96bfba0fe6.png)

```
Run gittools/actions/gitversion/execute@v0.9.5
Command: dotnet-gitversion D:/a/xxx/xxx /output json /output buildserver
C:\hostedtoolcache\windows\GitVersion.Tool\5.3.7\x64\dotnet-gitversion.exe D:/a/xxx/xxx /output json /output buildserver
INFO [11/08/20 19:27:51:72] Working directory: D:/a/xxx/xxx
INFO [11/08/20 19:27:51:75] Branch from build environment: refs/tags/0.4.0
INFO [11/08/20 19:27:51:75] Project root is: D:\a\xxx\xxx\
INFO [11/08/20 19:27:51:75] DotGit directory is: D:\a\xxx\xxx\.git
INFO [11/08/20 19:27:51:75] Begin: Normalizing git directory for branch 'refs/tags/0.4.0'
  INFO [11/08/20 19:27:51:79] One remote found (origin -> 'https://github.com/garyng/xxx').
  INFO [11/08/20 19:27:51:80] Skipping fetching, if GitVersion does not calculate your version as expected you might need to allow fetching or use dynamic repositories
  INFO [11/08/20 19:27:51:80] Updating local branch refs/heads/tags/0.4.0 to match ref refs/tags/0.4.0
  INFO [11/08/20 19:27:51:84] Skipping update of 'refs/remotes/origin/develop' as it already matches the remote ref.
  INFO [11/08/20 19:27:51:84] Skipping update of 'refs/remotes/origin/master' as it already matches the remote ref.
  INFO [11/08/20 19:27:51:84] HEAD points at branch 'refs/heads/tags/0.4.0'.
  INFO [11/08/20 19:27:51:84] End: Normalizing git directory for branch 'refs/tags/0.4.0' (Took: 87.78ms)
  INFO [11/08/20 19:27:51:86] Begin: Loading version variables from disk cache
    INFO [11/08/20 19:27:51:86] Begin: Deserializing version variables from cache file D:\a\xxx\xxx\.git\gitversion_cache\25B63416B7C10DF6A86DF1A05C9B459DDEE94609.yml
    INFO [11/08/20 19:27:51:93] End: Deserializing version variables from cache file D:\a\xxx\xxx\.git\gitversion_cache\25B63416B7C10DF6A86DF1A05C9B459DDEE94609.yml (Took: 71.53ms)
  INFO [11/08/20 19:27:51:93] End: Loading version variables from disk cache (Took: 72.11ms)
  INFO [11/08/20 19:27:51:94] Using latest commit on specified branch
  INFO [11/08/20 19:27:51:95] No branch configuration found for branch tags/0.4.0, falling back to default configuration
  INFO [11/08/20 19:27:51:96] Begin: Attempting to inherit branch configuration from parent branch
    INFO [11/08/20 19:27:51:97] HEAD is merge commit, this is likely a pull request using develop as base
    INFO [11/08/20 19:27:51:97] Begin: Finding branch source of 'develop'
    INFO [11/08/20 19:27:51:99] End: Finding branch source of 'develop' (Took: 14.07ms)
    INFO [11/08/20 19:27:51:99] Begin: Getting branches containing the commit '63f266552cc8574934a2f2e3b12d4b7e002b898b'.
      INFO [11/08/20 19:27:51:99] Trying to find direct branches.
      INFO [11/08/20 19:27:51:99] No direct branches found, searching through all branches.
      INFO [11/08/20 19:27:51:99] Searching for commits reachable from 'master'.
      INFO [11/08/20 19:27:52:00] The branch 'master' has a matching commit.
      INFO [11/08/20 19:27:52:00] Searching for commits reachable from 'origin/master'.
      INFO [11/08/20 19:27:52:00] The branch 'origin/master' has a matching commit.
    INFO [11/08/20 19:27:52:00] End: Getting branches containing the commit '63f266552cc8574934a2f2e3b12d4b7e002b898b'. (Took: 10.67ms)
    INFO [11/08/20 19:27:52:00] Found possible parent branches: master, origin/master
    WARN [11/08/20 19:27:52:00] Failed to inherit Increment branch configuration, ended up with: master, origin/master
Falling back to develop branch config
  INFO [11/08/20 19:27:52:00] End: Attempting to inherit branch configuration from parent branch (Took: 44.54ms)
Executing GenerateSetVersionMessage for 'GitHubActions'.

Executing GenerateBuildLogOutput for 'GitHubActions'.
Error: The `set-env` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
Error: The `set-env` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
Error: The `set-env` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
Error: The `set-env` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
Error: The `set-env` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
Error: The `set-env` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
Error: The `set-env` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
Error: The `set-env` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
Error: The `set-env` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
Error: The `set-env` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
Error: The `set-env` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
Error: The `set-env` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
Error: The `set-env` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
Error: The `set-env` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
Error: The `set-env` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
Error: The `set-env` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
Error: The `set-env` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
Error: The `set-env` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
Error: The `set-env` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
Error: The `set-env` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
Error: The `set-env` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
Error: The `set-env` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
Error: The `set-env` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
{
  "Major":0,
  "Minor":4,
  "Patch":0,
  "PreReleaseTag":"",
  "PreReleaseTagWithDash":"",
  "PreReleaseLabel":"",
  "PreReleaseNumber":"",
  "WeightedPreReleaseNumber":60000,
  "BuildMetaData":"",
  "BuildMetaDataPadded":"",
  "FullBuildMetaData":"Branch.tags-0.4.0.Sha.188651f87f7606fe2f2853d2dbd563f55350e74c",
  "MajorMinorPatch":"0.4.0",
  "SemVer":"0.4.0",
  "LegacySemVer":"0.4.0",
  "LegacySemVerPadded":"0.4.0",
  "AssemblySemVer":"0.4.0.0",
  "AssemblySemFileVer":"0.4.0.0",
  "FullSemVer":"0.4.0",
  "InformationalVersion":"0.4.0+Branch.tags-0.4.0.Sha.188651f87f7606fe2f2853d2dbd563f55350e74c",
  "BranchName":"tags/0.4.0",
  "EscapedBranchName":"tags-0-4-0",
  "Sha":"188651f87f7606fe2f2853d2dbd563f55350e74c",
  "ShortSha":"188651f",
  "NuGetVersionV2":"0.4.0",
  "NuGetVersion":"0.4.0",
  "NuGetPreReleaseTagV2":"",
  "NuGetPreReleaseTag":"",
  "VersionSourceSha":"188651f87f7606fe2f2853d2dbd563f55350e74c",
  "CommitsSinceVersionSource":8,
  "CommitsSinceVersionSourcePadded":"0008",
  "CommitDate":"2020-11-08"
}
  INFO [11/08/20 19:27:52:05] Done writing 
```

**Comment by GiorgioBertolotti** [comment]
For me the v0.9.5 solved all the errors, thanks!

**Comment by arturcic** [comment]
@garyng looks like you're using version 5.3.7. Can you install version 5.5.0 or better if you set version 5.x?

**Comment by garyng** [comment]
@arturcic Updating to `5.x` works! Thanks!

**Comment by asbjornu** [comment]
Excellent!

**Comment by willemduncan** [comment]
Thank all, but please don't close this until you also update the readme: https://github.com/GitTools/actions/blob/master/docs/examples/github/gitversion/index.md Right now it still links to action `0.9.4` and  gitversion `5.3.x`.

**Comment by arturcic** [comment]
@willemduncan do you mind sending us a PR with the suggested changes?

**Comment by willemduncan** [comment]
Sure will do.

**Comment by danielmarbach** [comment]
It seems I misunderstood how the build agent base operates. While I fixed the warning it no longer actively writes the key value pairs but just adds them to the log output. Unfortunately that was also no caught by the reviews on my PR.

@davidboike will raise a PR to fix this (we paired on it). Hopefully this time it will be fixed properly without destroying other things

**Comment by asbjornu** [comment]
I'm now experiencing [build failures](https://github.com/SwedbankPay/jekyll-plantuml-docker/pull/83/checks?check_run_id=1411117819#step:4:5) due to this problem, so it doesn't seem to be solved:

```
Error: Unable to process command '::set-env name=DOTNET_CLI_TELEMETRY_OPTOUT::1' successfully.
Error: The `set-env` command is disabled. Please upgrade to using Environment Files or opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
```

```
Error: Unable to process command '::set-env name=DOTNET_ROOT::../share/dotnet' successfully.
Error: The `set-env` command is disabled. Please upgrade to using Environment Files or opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
```

I suppose these are the perpetrators:

https://github.com/GitTools/actions/blob/b3e97697614c0696998c19a0f8e39defeb67b428/src/core/dotnet-tool.ts#L42-L44

https://github.com/GitTools/actions/blob/b3e97697614c0696998c19a0f8e39defeb67b428/src/core/dotnet-tool.ts#L125

These then invoke `BuildAgent.exportVariable`:

https://github.com/GitTools/actions/blob/b3e97697614c0696998c19a0f8e39defeb67b428/src/agent/github/build-agent.ts#L126-L128

Which brings me back to what I wrote in https://github.com/GitTools/actions/issues/213#issuecomment-721870455: Why would `core` be making calls to `::set-env`?

**Comment by arturcic** [comment]
@asbjornu from the build logs you referenced, it is used version 0.9.3 of the actions, not the latest 0.9.6

**Comment by asbjornu** [comment]
Hm, that's true @arturcic. But also really weird, as [the only thing changed in that PR](https://github.com/SwedbankPay/jekyll-plantuml-docker/pull/83/files#diff-551d1fcf87f78cc3bc18a7b332a4dc5d8773a512062df881c5aba28a6f5c48d7R28) is bumping from `0.9.3` to `0.9.6`.

**Comment by asbjornu** [comment]
Oh, we probably missed updating in some places.

**Comment by asbjornu** [comment]
Yep, bumping to 0.9.6 in all workflows fixed it. Sorry for the noise.

**Comment by Guilhermeslucas** [comment]
Anyone still having problem with this even after bumping to 0.9.6?

**Comment by asbjornu** [comment]
@Guilhermeslucas have you also bumped `versionSpec` to i.e. `5.x`?

**Comment by Guilhermeslucas** [comment]
Changing both the version and the versionSpec make it work like a charm!
